use_frameworks!

platform :ios, '15.0'

target 'RequestLibrary_Example' do
  pod 'RequestLibrary', :path => '../'
  pod 'Moya', '~> 15.0'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'RequestLibrary_Tests' do
    inherit! :search_paths    
  end
end
